### ISSUE TITLE
ublue: where is script and post folder.

### ISSUE THREAD

**Issue by jmaris** [MiMillieuh/acpi_call-fedora#2]
as per title: where is the script and post folder you mention?

**Comment by MiMillieuh** [comment]
Ublue (now bluebuild) has changed a lot since the writing of that tutorial : 

it's now in `config/scripts` and you need to add a script to you recipe.yml : 

```
  - type: script
    scripts:
      - acpi_call-module.sh
```

You can look at my custom image if it can help : [AME-TataruOS](https://github.com/MiMillieuh/AME-TataruOS/tree/main)

**Comment by jmaris** [comment]
Cheers :)
